// <auto-generated />
namespace CRUDORM_Projeckt_4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class CRUDORM_Projeckt_4_11a : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CRUDORM_Projeckt_4_11a));
        
        string IMigrationMetadata.Id
        {
            get { return "202306020834166_CRUDORM_Projeckt_4_11a"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
